// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7E0eunXZSar4UhGiJV_jhMhbCetUYXDI',
    appId: '1:1061766343415:web:4bc24d6d7fc91a9e7c81f2',
    messagingSenderId: '1061766343415',
    projectId: 'manggatect-admin',
    authDomain: 'manggatect-admin.firebaseapp.com',
    storageBucket: 'manggatect-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3iIEqT3sKL9eFG-_U3VLpiP-tsiZrjo',
    appId: '1:1061766343415:android:99182357d9c719ae7c81f2',
    messagingSenderId: '1061766343415',
    projectId: 'manggatect-admin',
    storageBucket: 'manggatect-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_9uZECqe3yXEz-XM8holG4rZY32o2_aU',
    appId: '1:1061766343415:ios:565540b789c2096c7c81f2',
    messagingSenderId: '1061766343415',
    projectId: 'manggatect-admin',
    storageBucket: 'manggatect-admin.appspot.com',
    iosBundleId: 'com.example.manggatectv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_9uZECqe3yXEz-XM8holG4rZY32o2_aU',
    appId: '1:1061766343415:ios:565540b789c2096c7c81f2',
    messagingSenderId: '1061766343415',
    projectId: 'manggatect-admin',
    storageBucket: 'manggatect-admin.appspot.com',
    iosBundleId: 'com.example.manggatectv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7E0eunXZSar4UhGiJV_jhMhbCetUYXDI',
    appId: '1:1061766343415:web:5eb7f6e713dcbd747c81f2',
    messagingSenderId: '1061766343415',
    projectId: 'manggatect-admin',
    authDomain: 'manggatect-admin.firebaseapp.com',
    storageBucket: 'manggatect-admin.appspot.com',
  );
}
